---
- hosts: memcache
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Install from apk.
      apk:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "memcached"
      notify:
        - clear apk cache
    - name: Install telnet from testing repo.
      shell: >
        apk add -U --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing inetutils-telnet
      notify:
        - clear apk cache
    - name: Ensure key directories are owned by varnish
      file:
        path: "{{ item }}"
        state: directory
        owner: "memcache"
        group: "memcache"
        mode: "u=rwx,g=rwx,o=r"
        recurse: yes
      loop:
        - "/etc/memcache"
    # Deploy the run command at build time using defaults in the template.
    # This way, the container can still run via FLIGHTDECK_SKIP_ENTRYPOINT.
    - name: Deploy key scripts.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "memcache"
        group: "memcache"
        mode: "u=rwx,g=rwx,o="
      loop:
        - src: "templates/memcache-foreground.sh.j2"
          dest: "/etc/memcache/memcache-foreground.sh"
  handlers:
    - name: clear apk cache
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
